/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import styles from '../styles/Home.module.css'

export default function Home() {
	const handleBannerButtonClick = () => {
		console.log('clicked')
	}
	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee pro</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<Banner
					buttonText={'Find stores nearby'}
					handleOnClick={handleBannerButtonClick}
				/>
				<div className={styles.heroImage}>
					<Image src='/static/hero.png' width={800} height={400} />
				</div>
			</main>
		</div>
	)
}
